/*
 * Copyright 2026 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v17.0
processor: RW612
package_id: RW612ETA2I
mcu_data: ksdk2_0
processor_version: 25.06.10
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_io_mux.h"
#include "fsl_inputmux.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: E5, peripheral: FLEXCOMM3, signal: USART_RXD, pin_signal: GPIO_24}
  - {pin_num: G13, peripheral: GAU_ACOMP, signal: 'POS_IN, 0', pin_signal: GPIO_42}
  - {pin_num: G13, peripheral: GAU_ACOMP, signal: 'NEG_IN, 0', pin_signal: GPIO_42}
  - {pin_num: G13, peripheral: GAU_GPADC0, signal: 'IN, 0', pin_signal: GPIO_42}
  - {pin_num: K12, peripheral: PINT, signal: 'PINT, 2', pin_signal: GPIO_50}
  - {pin_num: N8, peripheral: CLKCTL1, signal: CLKOUT, pin_signal: GPIO_12}
  - {pin_num: L9, peripheral: FLEXCOMM1, signal: SPI_SCK, pin_signal: GPIO_7}
  - {pin_num: M4, peripheral: FLEXCOMM1, signal: SPI_MOSI, pin_signal: GPIO_9}
  - {pin_num: L5, peripheral: FLEXCOMM1, signal: SPI_SSELN0, pin_signal: GPIO_6}
  - {pin_num: M6, peripheral: FLEXCOMM1, signal: SPI_MISO, pin_signal: GPIO_8}
  - {pin_num: K8, peripheral: CTIMER3, signal: 'MATCH, 0', pin_signal: GPIO_52}
  - {pin_num: J3, peripheral: FLEXCOMM2, signal: I2C_SDA, pin_signal: GPIO_16}
  - {pin_num: H2, peripheral: FLEXCOMM2, signal: I2C_SCL, pin_signal: GPIO_17}
  - {pin_num: J11, peripheral: LCDIC, signal: LCD_SPI_RESET, pin_signal: GPIO_44}
  - {pin_num: D14, peripheral: LCDIC, signal: LCD_SPI_SS, pin_signal: GPIO_49}
  - {pin_num: F12, peripheral: LCDIC, signal: LCD_SPI_DATA, pin_signal: GPIO_46}
  - {pin_num: H10, peripheral: LCDIC, signal: LCD_SPI_TE, pin_signal: GPIO_45}
  - {pin_num: E13, peripheral: LCDIC, signal: LCD_SPI_DC, pin_signal: GPIO_47}
  - {pin_num: D13, peripheral: LCDIC, signal: LCD_SPI_SCK, pin_signal: GPIO_48}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : 
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 */
void BOARD_InitPins(void)
{
    /* pmux clock control: Enable clock */
    CLOCK_EnableClock(kCLOCK_InputMux);
    /* Initialize FC1_SPI_SS0 functionality on pin GPIO_7, GPIO_9, GPIO_6, GPIO_8 (pin L9_M4_L5_M6) */
    IO_MUX_SetPinMux(IO_MUX_FC1_SPI_SS0);
    /* Initialize FC2_I2C_16_17 functionality on pin GPIO_16, GPIO_17 (pin J3_H2) */
    IO_MUX_SetPinMux(IO_MUX_FC2_I2C_16_17);
    /* Initialize FC3_USART_DATA functionality on pin GPIO_24 (pin E5) */
    IO_MUX_SetPinMux(IO_MUX_FC3_USART_DATA);
    /* Initialize CT3_MAT0_OUT functionality on pin GPIO_52 (pin K8) */
    IO_MUX_SetPinMux(IO_MUX_CT3_MAT0_OUT);
    /* Initialize LCD_SPI functionality on pin GPIO_44, GPIO_49, GPIO_46, GPIO_45, GPIO_47, GPIO_48 (pin
     * J11_D14_F12_H10_E13_D13) */
    IO_MUX_SetPinMux(IO_MUX_LCD_SPI);
    /* Initialize GPIO50 functionality on pin GPIO_50 (pin K12) */
    IO_MUX_SetPinMux(IO_MUX_GPIO50);

    MCI_IO_MUX->C_TIMER_IN = ((MCI_IO_MUX->C_TIMER_IN &
                               /* Mask bits to zero which are setting */
                               (~(MCI_IO_MUX_C_TIMER_IN_CT_INP2_SEL_MASK)))

                              /* sel GPIO-12 as ct_inp2: 0x00u */
                              | MCI_IO_MUX_C_TIMER_IN_CT_INP2_SEL(0x00u));

    MCI_IO_MUX->C_TIMER_OUT = ((MCI_IO_MUX->C_TIMER_OUT &
                                /* Mask bits to zero which are setting */
                                (~(MCI_IO_MUX_C_TIMER_OUT_CT0MAT2_SEL_MASK)))

                               /* sel GPIO-12 as ct0mat2: 0x00u */
                               | MCI_IO_MUX_C_TIMER_OUT_CT0MAT2_SEL(0x00u));

    MCI_IO_MUX->FSEL =
        ((MCI_IO_MUX->FSEL &
          /* Mask bits to zero which are setting */
          (~(MCI_IO_MUX_FSEL_SEL_USB_MASK | MCI_IO_MUX_FSEL_SEL_LCD_8080_MASK | MCI_IO_MUX_FSEL_SEL_SDIO_MASK)))

         /* select GPIO-12 as usb utmi_drvvbus: 0x00u */
         | MCI_IO_MUX_FSEL_SEL_USB(0x00u)
         /* select GPIO-42/43/44/45/46/47/48/49/51/52/53/54/56/57 as lcd_8080 function: 0x00u */
         | MCI_IO_MUX_FSEL_SEL_LCD_8080(0x00u)
         /* select GPIO-12/15/16/17/18/19/20 as sdio function: 0x00u */
         | MCI_IO_MUX_FSEL_SEL_SDIO(0x00u));

    MCI_IO_MUX->GPIO_GRP0 = ((MCI_IO_MUX->GPIO_GRP0 &
                              /* Mask bits to zero which are setting */
                              (~(MCI_IO_MUX_GPIO_GRP0_SEL_12_MASK)))

                             /* pio0[31:0] selection, high valid; sel[i]->pio0[i]->GPIO[i]: 0x00u */
                             | MCI_IO_MUX_GPIO_GRP0_SEL(0x00u));

    MCI_IO_MUX->GPIO_GRP1 = ((MCI_IO_MUX->GPIO_GRP1 &
                              /* Mask bits to zero which are setting */
                              (~(MCI_IO_MUX_GPIO_GRP1_SEL_10_MASK)))

                             /* pio0[63:32] selection, high valid; sel[i]->pio0[i+32]->GPIO[i+32]: 0x00u */
                             | MCI_IO_MUX_GPIO_GRP1_SEL(0x00u));

    MCI_IO_MUX->S_GPIO = ((MCI_IO_MUX->S_GPIO &
                           /* Mask bits to zero which are setting */
                           (~(MCI_IO_MUX_S_GPIO_SEL_10_MASK)))

                          /* spio0[31:0] selection, high valid; sel[i]->spio0[i]->GPIO[i+32]: 0x00u */
                          | MCI_IO_MUX_S_GPIO_SEL(0x00u));

    SOCCTRL->MCI_IOMUX_EN0 = ((SOCCTRL->MCI_IOMUX_EN0 &
                               /* Mask bits to zero which are setting */
                               (~(SOCCIU_MCI_IOMUX_EN0_EN_21_0_12_MASK)))

                              /* Bitwise enable control for mci_io_mux GPIO[21:0]: 0x00u */
                              | SOCCIU_MCI_IOMUX_EN0_EN_21_0(0x00u));

    SOCCTRL->MCI_IOMUX_EN1 = ((SOCCTRL->MCI_IOMUX_EN1 &
                               /* Mask bits to zero which are setting */
                               (~(SOCCIU_MCI_IOMUX_EN1_EN_10_MASK)))

                              /* Bitwise enable control for mci_io_mux GPIO[63:32]: 0x00u */
                              | SOCCIU_MCI_IOMUX_EN1_EN(0x00u));

    SOCCTRL->TST_TSTBUS_CTRL2 =
        ((SOCCTRL->TST_TSTBUS_CTRL2 &
          /* Mask bits to zero which are setting */
          (~(SOCCIU_TST_TSTBUS_CTRL2_CLK_OUT_SEL_MASK | SOCCIU_TST_TSTBUS_CTRL2_CLK_OUT_PAGE_SEL_MASK | SOCCIU_TST_TSTBUS_CTRL2_CLK_OUT_EN_MASK | SOCCIU_TST_TSTBUS_CTRL2_CLK_OUT_EN_ALT_MASK)))

         /* PAGE 0: 0x0Eu */
         | SOCCIU_TST_TSTBUS_CTRL2_CLK_OUT_SEL(0x0Eu)
         /* Clock out test page sel: 0x03u */
         | SOCCIU_TST_TSTBUS_CTRL2_CLK_OUT_PAGE_SEL(0x03u)
         /* Clock Out Enable: 0x01u */
         | SOCCIU_TST_TSTBUS_CTRL2_CLK_OUT_EN(0x01u)
         /* Clock Out Enable: 0x00u */
         | SOCCIU_TST_TSTBUS_CTRL2_CLK_OUT_EN_ALT(0x00u));
    /* PIO1_18 is selected for PINT input 2 */
    INPUTMUX_AttachSignal(INPUTMUX, 2U, kINPUTMUX_GpioPort1Pin18ToPintsel);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
