/*
 * Copyright 2026 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief pio0[31:0] selection, high valid; sel[i]->pio0[i]->GPIO[i] Mask for item 12. */
#define MCI_IO_MUX_GPIO_GRP0_SEL_12_MASK 0x1000u
/*!
 * @brief pio0[63:32] selection, high valid; sel[i]->pio0[i+32]->GPIO[i+32] Mask for item 10. */
#define MCI_IO_MUX_GPIO_GRP1_SEL_10_MASK 0x0400u
/*!
 * @brief spio0[31:0] selection, high valid; sel[i]->spio0[i]->GPIO[i+32] Mask for item 10. */
#define MCI_IO_MUX_S_GPIO_SEL_10_MASK 0x0400u
/*!
 * @brief Bitwise enable control for mci_io_mux GPIO[21:0] Mask for item 12. */
#define SOCCIU_MCI_IOMUX_EN0_EN_21_0_12_MASK 0x1000u
/*!
 * @brief Bitwise enable control for mci_io_mux GPIO[63:32] Mask for item 10. */
#define SOCCIU_MCI_IOMUX_EN1_EN_10_MASK 0x0400u

/*!
 * @brief 
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M33 */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
